swagger: '2.0'
info:
  version: '0.1.0'
  title: User API
  description: An API for users
host: localhost:8080
basePath: /api
schemes:
  - http
  - https
paths:
  /registrations:
    post:
      tags:
        - user
      description: Create a new user.
      summary: Create user
      operationId: registerUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: Bad Request

  /login:
    post:
      tags:
        - user
      description: Login user with username and password, returns a jwt token for authorizazion
      summary: Login with credentials
      operationId: loginUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          description: credentials
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/JwtToken'
        '400':
          description: Bad Credentials
        '404':
          description: Not found

  /passwords:
    patch:
      tags:
        - user
      summary: change user Password
      description: Change user password only if he is autenticated.
      operationId: changePassword
      consumes:
        - text/plain
      parameters:
        - name: newPassword
          in: body
          required: true
          description: User's new password.
          schema:
            type: string
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request







  /users:
    get:
      tags:
        - admin
      summary: Get all users
      description: An admin operation to fetch all users in the database
      operationId: findAllUsers
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '400':
          description: Not found

    post:
      tags:
        - admin
      summary: Create user
      description: Create a new user.
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: Bad Request

  /users/{username}:
    get:
      tags:
        - admin
      summary: Get user by username
      description: Get user using his username.
      operationId: getUserByName
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: The username of the user to be fetched.
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            items:
              $ref: '#/definitions/User'
    patch:
      tags:
        - changePassword
      summary: change user password
      description: Change user password only if he is autenticated.
      operationId: changeUserPassword
      parameters:
        - name: username
          in: path
          description: "username of the user who wishes to change his password"
          required: true
          type: "string"
        - name: password
          in: body
          description: New password
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK


definitions:
  User:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
  JwtToken:
    type: object
    properties:
      token:
        type: string