swagger: '2.0'
info:
  version: '0.1.0'
  title: User API
  description: An API for users.
host: localhost:6060
basePath: /api
schemes:
  - http

securityDefinitions:
  Jwt:
    type: apiKey
    name: Authorization
    in: header
    description: Requests should pass an authorization header.

paths:
  /registrations:
    post:
      tags:
        - user
      description: Create a new user.
      summary: Create user
      operationId: registerUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: Bad Request

  /authentications:
    post:
      tags:
        - user
      description: Login user with username and password, returns a jwt token for authorizazion
      summary: Login with credentials
      operationId: loginUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          description: credentials
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/JwtToken'
        '401':
          description: Bad Credentials
        '404':
          description: Not found

  /passwords:
    patch:
      tags:
        - user
      security:
        - Jwt: []
      summary: change user Password
      description: Change user password only if he is autenticated.
      operationId: changePassword
      consumes:
        - text/plain
      parameters:
        - name: newPassword
          in: body
          required: true
          description: User's new password.
          schema:
            type: string
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request

  /profiles:
    get:
      tags:
        - user
      security:
        - Jwt: []
      summary: Get user profile.
      description: Get the user profile info.
      operationId: getUserProfile
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: object
            items:
              $ref: '#/definitions/User'
        '401':
          description: not authenticated

    put:
      tags:
        - user
      security:
        - Jwt: []
      summary: Update user profile
      description: Update user profile info like firstname, lastname or email.
      operationId: updateProfile
      consumes:
        - application/json
      parameters:
        - name: profileUpdate
          in: body
          required: true
          description: updates to the user profile
          schema:
            $ref: '#/definitions/ProfileUpdate'
      responses:
        '200':
          description: updated
        '400':
          description: Bad Request

  /users:
    get:
      tags:
        - admin
      security:
        - Jwt: []
      summary: Get all users
      description: An admin operation to fetch all users in the database
      operationId: findAllUsers
      produces:
        - application/json
      parameters:
        - in: query
          name: page
          type: integer
          required: false
          default: 0
          minimum: 0
          description: The number of the displayed page.
        - in: query
          name: pageSize
          type: integer
          required: false
          default: 20
          minimum: 0
          maximum: 100
          description: The number of items to be displayed on one page.
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '404':
          description: Not found

    post:
      tags:
        - admin
      security:
        - Jwt: []
      summary: Create user
      description: Create a new user.
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: created
          schema:
            type: object
        '400':
          description: Bad Request

  /users/{username}:
    parameters:
      - name: username
        in: path
        description: The username of the user to be fetched.
        required: true
        type: string
    get:
      tags:
        - admin
      security:
        - Jwt: []
      summary: Get user by username
      description: Get user using his username.
      operationId: getUserByName
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: object
            items:
              $ref: '#/definitions/User'
        '400':
          description: Bad Request
        '404':
          description: Not Found
    delete:
      tags:
        - admin
      security:
        - Jwt: []
      summary: Delete a user
      description: Delete a user by username
      operationId: deleteUser
      responses:
        '204':
          description: success
        '400':
          description: Bad Request
        '404':
          description: Not Found

    patch:
      tags:
        - admin
      security:
        - Jwt: []
      summary: Block or unblock a user
      description: Block or unblock a user. A blocked user cannot access the api unless unblocked again by the admin.
      operationId: updateUserBlockedStatus
      parameters:
        - in: query
          name: blocked
          type: boolean
          required: true
          description: boolean describing whether user should be blocked or not.
      responses:
        200:
          description: User Blocked
        400:
          description: Bad Request
        404:
          description: Not Found


definitions:
  User:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
  ProfileUpdate:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
  JwtToken:
    type: object
    properties:
      token:
        type: string